#!/usr/bin/bash

_aoc_cmp() {
  _script_commands=$(./advent_of_code -h)

  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "${_script_commands}" -- ${cur}) )
  return 0
}

complete -o nospace -F _aoc_cmp ./advent_of_code -h
