[project]
name = "aoc-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Emilia Glibowska", email = "emilia.glibowska@elmark.com.pl" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
aoc-2025 = "aoc_2025:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
